# Generated by Django 4.1.7 on 2023-03-26 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clients_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='client',
            new_name='user',
        ),
    ]
